---
sidebar: sidebar 
permalink: docs/task_upgrade_element_latest_healthtools.html 
summary: 'Come parte di un aggiornamento del sistema, è necessario eseguire l"aggiornamento al software HealthTools per NetApp Element più recente.' 
keywords: netapp, HealthTools upgrade, sfupdate-healthtools, element 
---
= Effettua l'aggiornamento alla versione più recente di HealthTools
:allow-uri-read: 


[role="lead"]
Prima di iniziare l'aggiornamento dello spazio di archiviazione degli elementi, è necessario aggiornare la suite HealthTools. L'aggiornamento di HealthTools è necessario solo se il nodo di gestione e il software Element in esecuzione sono 11.1 o precedenti. HealthTools non è necessario per eseguire gli aggiornamenti degli elementi utilizzando NetApp Hybrid Cloud Control.

.Di cosa hai bisogno
* Si sta eseguendo il nodo di gestione 11.0, 11.1 o versione successiva.
* I servizi di gestione sono stati aggiornati almeno alla versione 2,1.326.
+
Gli aggiornamenti di NetApp Hybrid Cloud Control non sono disponibili nelle versioni precedenti dei service bundle.

* È stata scaricata la versione più recente di https://mysupport.netapp.com/site/products/all/details/element-healthtools/downloads-tab["HealthTools"^] e copiata il file di installazione nel nodo di gestione.
+

TIP: È possibile controllare la versione installata localmente di HealthTools eseguendo il `sfupdate-healthtools -v` comando.

* Per utilizzare HealthTools con i siti oscuri, è necessario eseguire i seguenti passaggi aggiuntivi:
+
** Scaricare un link:https://library.netapp.com/ecm/ecm_get_file/ECMLP2840740["File JSON"^] dal sito di supporto NetApp su un computer che non è il nodo di gestione e rinominarlo in `metadata.json`.
** Far funzionare il nodo di gestione al sito buio.




.A proposito di questa attività
I comandi della suite HealthTools richiedono privilegi di escalation per l'esecuzione. Prefazione dei comandi `sudo` o escalation dell'utente a root Privileges.


NOTE: La versione di HealthTools utilizzata potrebbe essere più aggiornata rispetto all'input e alla risposta di esempio riportati di seguito.

.Fasi
. Eseguire `sfupdate-healthtools <path to install file>` il comando per installare il nuovo software HealthTools.
+
Esempio di input:

+
[listing]
----
sfupdate-healthtools /tmp/solidfire-healthtools-2020.03.01.09.tgz
----
+
Esempio di risposta:

+
[listing]
----
Checking key signature for file /tmp/solidfirehealthtools-2020.03.01.09/components.tgz
installing command sfupdate-healthtools
Restarting on version 2020.03.01.09
sfupdate-healthtools /sf/bin/sfupdate-healthtools -r 2020.03.01.09
installing command sfupgradecheck
installing command sfinstall
installing command sfresetupgrade
----
. Eseguire `sfupdate-healthtools -v` il comando per verificare che la versione installata sia stata aggiornata.
+
Esempio di risposta:

+
[listing]
----
Currently installed version of HealthTools:
2020.03.01.09
----


[discrete]
== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Pagina delle risorse NetApp HCI"^]

