---
sidebar: sidebar 
permalink: docs/hcc_dashboard.html 
summary: Puoi rispondere agli avvisi sulla dashboard di controllo del cloud ibrido. 
keywords: netapp, hci, hcc, on premise, alerts, warnings 
---
= Rispondere agli avvisi sulla dashboard di controllo del cloud ibrido
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puoi visualizzare e rispondere rapidamente agli avvisi sul pannello di controllo del cloud ibrido.



== Fasi

. Accedere alla https://fabric.netapp.io["NetApp Fabric Orchestrator"^] pagina di accesso.
. Immettere le credenziali di accesso a Cloud Central e selezionare *Login*.
+

TIP: Se non compare alcun sistema nell'elenco, assicurarsi che l'amministratore di NetApp HCI sia aggiunto all'account NetApp Cloud Central.

. Se non si dispone di un account Cloud Central, nella pagina di accesso a Cloud Central selezionare *Iscriviti*.
+
Con Cloud Central, puoi configurare gli account come singoli account o come account Federated:

+
.. È possibile creare un nuovo account con nome, e-mail e password, quindi si sarà connessi. Questo è il tipo di account più semplice.
.. Se fai parte di un'organizzazione Cloud Central Federated, inserisci il tuo indirizzo e-mail e sarai indirizzato all'accesso dell'organizzazione.


. Da altri prodotti Cloud Central, selezionare *prodotti* > *NetApp Fabric Orchestrator*.


[discrete]
== Trova ulteriori informazioni

* https://cloud.netapp.com/home["NetApp Cloud Central"^]
* https://docs.netapp.com/us-en/cloud/["Documentazione cloud di NetApp"^]

